<!DOCTYPE html>
<html lang="en">
<!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
wet-boew.github.com/wet-boew/License-eng.txt / wet-boew.github.com/wet-boew/Licence-fra.txt -->
<!-- DataAjaxFragmentStart -->

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html"><strong>Work Central</strong></a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html#tools"><strong>Tools</strong></a></h4>
  <ul>
	<li><a href="https://achatsendirect-e-purchasing.gc.ca/e_purchasing.formproc?/ECAT?">E-Purchasing</a></li>
	<li><a href="http://www.tpsgc-pwgsc.gc.ca/biens-property/sngp-npms/index-eng.html">National Project Management System</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/branch/acquisitions/text/ofpt-e.html">Procurement Tools</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/finance/text/sigma/index-eng.html">Sigma System</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html#rm"><strong>Reference Materials</strong></a></h4>
  <ul>
	<li><a href="http://publiservice.tpsgc-pwgsc.gc.ca/ipm-dpi/index-eng.html">Departmental Policies</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/finance/text/ges-man/taux-rates-eng.html">Interest Rates</a></li>
	<li><a href="http://publiservice.tpsgc-pwgsc.gc.ca/rg/manuels-manuals/index-eng.html">Receiver General Manual</a></li>
	<li><a href="https://buyandsell.gc.ca/policy-and-guidelines/supply-manual">Supply Manual</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html#ts"><strong>Technical Support</strong></a></h4>
  <ul>
	<li><a href="http://csti-itsc.tpsgc-pwgsc.gc.ca/iprint/index.aspx?lang=eng">Install Network Printer</a></li>
	<li><a href="http://ossro-dsbl.etg.gc.ca/pwgsc/start.aspx"><abbr title="information technology">IT</abbr> Service Request</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/ti-it/mpls-pss/text/main-e.html">Password Reset</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/ti-it/mv-vm/index-eng.html">Voicemail Setup</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html#is"><strong>Internal Services</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/branch/cspc/dsg-cs/text/mtrl-e.html#s1">Acquisitions Card</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/branch/cspc/cims/sgc-mms/crr-e.html">Mail and Courier</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/branch/cspc/dsg-cs/text/mnstrcrprt-e.html">Office Space</a></li>
	<li><a href="http://btb.gc.ca/btb.php?lang=eng&cont=268">Translation and Terminology</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html#comms"><strong>Communications</strong></a></h4>
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/immng-clsg-eng.html">Brand Toolbox</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/ps-eng.html">Events</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/rm-mr-eng.html">Media Relations</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/ms-sm/ms-sm-eng.html">Social Media</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html#bt"><strong>Business Travel</strong></a></h4>
  <ul>
	<li><a href="http://rehelv-acrd.tpsgc-pwgsc.gc.ca/index-eng.aspx ">Accommodations</a></li>
	<li><a href="http://rehelv-acrd.tpsgc-pwgsc.gc.ca/rechercher-search-4-eng.aspx">Car Rental</a></li>
	<li><a href="http://publiservice.tpsgc-pwgsc.gc.ca/bi-rp/publications/stat-park-e.html">Parking</a></li>
	<li><a href="https://sts-tav.gc.ca/index-eng.html">Travel AcXess</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html#fs"><strong>Facilities and Security</strong></a></h4>
  <ul>
	<li><a href="https://reservations.pwgsc.gc.ca/welcome.cfm?language=ENGLISH">Boardroom Reservation</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dsm-csd/index-eng.html">Departmental Security</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/planevacu-evacuplan-eng.html">Emergency Evacuation</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dsm-csd/persec-secpers-eng.html">Identification Cards</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html#mc"><strong>Management Centre</strong></a></h4>
  <ul>
	<li><a href="http://source-app.tpsgc-pwgsc.gc.ca/dotationexpress-expressstaffing/text/index-eng.cfm">Express Staffing</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/planification-planning/planification-planning-eng.html">Human Resources Planning</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/rendement-performance/gr-pm-eng.html">Performance Management</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/vousetes-areyou/gestionnaires-manager-eng.html">Resources for Managers</a></li>
  </ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-eng.html"><strong>Work Central - Main page</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html"><strong>Employee Corner</strong></a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html#pp"><strong>Pay and Pension</strong></a></h4>
  <ul>
	<li><a href="http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/awr-cwa/index-eng.html">Compensation Web Applications</a></li>
	<li><a href="http://pensionetavantages-pensionandbenefits.gc.ca/accueil-home-eng.html">Pension</a></li>
	<li><a href="http://publiservice.tbs-sct.gc.ca/pubs_pol/hrpubs/coll_agre/rates-taux-eng.asp">Rates of Pay</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html#bi"><strong>Benefits and Insurance</strong></a></h4>
  <ul>
	<li><a href="http://publiservice.tbs-sct.gc.ca/pubs_pol/hrpubs/coll_agre/siglist-eng.asp">Collective Agreements</a></li>
	<li><a href="http://www.tbs-sct.gc.ca/hr-rh/bp-rasp/benefits-avantages/dip-rai/dip-rai-eng.asp">Disability Insurance</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/avantages-benefits/conges-leave/conges-leave-eng.html">Leave</a></li>
	<li><a href="http://publiservice.tbs-sct.gc.ca/hr-rh/bp-rasp/mb-mav/pml-cpcm-eng.asp">Maternity and Parental Leave</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html#tc"><strong>Training and Career</strong></a></h4>
  <ul>
	<li><a href="http://www.csps-efpc.gc.ca/index-eng.aspx">Canada School of Public Service</a></li>
	<li><a href="http://coursebrowser.pwgsc.gc.ca/welcome.htm?&language=en">Course Browser</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/languages/formation-guideline-eng.html">Language Training</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/apprentissage-learning/papms-plpp-eng.html">Personal Learning Plans</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html#he"><strong>Hiring and Employment</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/gest-car-manag/index-eng.html">Career Management</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/classification/class-org-eng.html">Classification</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/competences-competencies/index-eng.html">Competencies</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/travail-labour/sites-eng.html">Union Information</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html#hw"><strong>Health and Wellness</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/ergonomie-ergonomics-eng.html">Ergonomic Assessment</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/soins-aid-eng.html">First Aid</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/index-eng.html">Occupational Health and Safety</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/equit-divers/opma-da-eng.html">Work-related Aids</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html#hrsp"><strong><abbr title="Human Resources">HR</abbr> Services and Programs</strong></a></h4>
  <ul>
    <li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/recompenses-awards/recompenses-awards-eng.html">Awards and Recognition</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/equit-divers/eme-ee-eng.html">Equity and Diversity</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/languages/lo-ol-eng.html">Official Languages</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/val-eth/index-eng.html">Values and Ethics</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html#wi"><strong>Workplace Issues</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/confli/bgcmt-owcm-eng.html">Conflict Resolution</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/aide-assistance/paeo-eoap-eng.html">Employee and Organizational Assistance Program</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/travail-labour/reglediffer-guidedispres-eng.html">Harassment</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dgs-dob/di-id/divulgation-disclosure-eng.html">Internal Disclosure</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/travail-labour/rt-lr-eng.html">Labour Relations</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html#policies"><strong>Policies</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/val-eth/code-cond-eng.html">Code of Conduct</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/lstpolsst-lstpolhas-eng.html">Health and Safety</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/philo-eng.html">Philosophy and Commitments</a></li>
	<li><a href="http://www.tbs-sct.gc.ca/chro-dprh/pol-eng.asp">Treasury Board</a></li>
  </ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-eng.html"><strong>Employee Corner - Main page</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-eng.html"><strong>News</strong></a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-eng.html#nn"><strong>National News</strong></a></h4>
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/smsmd-dmadm/index-eng.html">From the <abbr title="Deputy Ministers">DMs</abbr>' Desk</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/mm-mm/index-eng.html">Message from the Minister</a></li>
	<li><a href="http://www.infomedia.gc.ca/pwgsc-tpsgc/index-eng.aspx">NewsDesk</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/dlc-ink/index-eng.html"><abbr title="Public Works and Government Services Canada">PWGSC</abbr> In the Know</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-eng.html#dn"><strong>Departmental News</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/ssc-css/bulletinssc-css-eng.html">Client Service Strategy</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/finance/index-eng.html">Finance</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/sit-its/aprps-abt/vdtt-fcs/index-eng.html">Information Technology</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/bi-rp/bulletin-newsletter/index-eng.html">Real Property</a></li>
	<li><a href="http://atrium.gc.ca/atrium.php?page=nouvelles_news&lang=en">Translation Bureau</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-eng.html#rn"><strong>Regional News</strong></a></h4>
  <ul>
	<li><a href="http://intranet.atl.pwgsc.gc.ca/breakers-brisants/home-accueil">Atlantic</a></li>
	<li><a href="http://orion.ont.pwgsc.gc.ca/ont/news-nouvelles/index-eng.cfm">Ontario</a></li>
	<li><a href="http://renew.pac.pwgsc.gc.ca/applications/news/index.cfm">Pacific</a></li>
	<li><a href="http://gasoti-amitos.que.tpsgc.gc.ca/entrenous/oeil_glimpse/dernnouvlatestnews/tabid/665/language/en-CA/Default.aspx">Quebec</a></li>
	<li><a href="http://thewire.wst.pwgsc.gc.ca/news/mynews/rextra.aspx">Western</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-eng.html#events"><strong>Events</strong></a></h4>
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/smsmd-dmadm/2020/index-eng.html">Blueprint 2020</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/dlc-ink/ce-ec/index-eng.html">Events Calendar</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/ccmtgc-gcwcc/index-eng.html">Government of Canada Workplace Charitable Campaign (GCWCC)</a></li>
  </ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-eng.html"><strong>News - Main page</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-eng.html"><strong>Communities</strong></a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-eng.html#networks"><strong>Networks</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/quisommes-whoweare/autochtones-aboriginal-eng.html">Aboriginal Peoples</a></li>
	<li><a href="http://mcn-rcg.pwgsc.gc.ca/index.cfm/eng/">Managers' Network</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/quisommes-whoweare/handicap-disabil-eng.html">Persons with Disabilities</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/quisommes-whoweare/fierte-pride-eng.html">PRIDE at Work</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/quisommes-whoweare/minorites-minorities-eng.html">Visible Minorities</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rnj-nyn/index-eng.html">Youth</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-eng.html#sm"><strong>Social Media</strong></a></h4>
  <ul>
	<li><a href="http://elgg.srv.gc.ca/elgg17/">GCConnex</a></li>
	<li><a href="http://www.gcforums.gc.ca/default.aspx?l=e">GCForums</a></li>
	<li><a href="http://www.gcpedia.gc.ca/wiki/Main_Page">GCPedia</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/bhd-slb/index-eng.html">Senior Leaders' Blog</a></li>
	<li><a href="http://infowiki.tpsgc-pwgsc.gc.ca/homepage.action?lang=eng">Infowiki</a></li>
	<li><a href="https://twitter.com/@PWGSC_TPSGC">Twitter</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-eng.html#committees"><strong>Committees</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/comite-committee-eng.html">Disability Management and Duty to Accommodate Review Committee</a></li>
  <li><a href="http://www.gcpedia.gc.ca/wiki/EIPP_Working_Group">Electronic Invoice Presentment and Payment Initiative Working Group</a></li>
  <li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/equit-divers/cceme-jcee-eng.html">Joint Committee on Employment Equity and Diversity</a></li>
  <li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/comitesst-hascommittee-eng.html">Occupational Health and Safety Committees</a></li>
  <li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/travail-labour/afpc-psac-eng.html">Public Service Alliance of Canada&nbsp;&ndash; Labour-Management Consultation Committees</a></li>
  </ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-eng.html"><strong>Communities - Main page</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/st-ps/index-eng.html"><strong><abbr title="Public Works and Government Services Canada">PWGSC</abbr> Services</strong></a></h3><div class="mb-sm">
<div class="span-2">
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/branch/abc/text/index-e.html">Accounting, Banking and Compensation</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/branch/acquisitions/text/index-e.html">Acquisitions</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/index-eng.html">Communications</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/branch/cspc/text/index-e.html">Corporate Services and Strategic Policy</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dgs-dob/index-eng.html">Departmental Oversight</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/finance/index-eng.html">Finance</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/index-eng.html">Human Resources</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/sit-its/index-eng.html">Information Technology Services</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dgsi-isb/index-eng.html">Integrated Services</a></li>
	<li><a href="http://www.tpsgc-pwgsc.gc.ca/collineduparlement-parliamenthill/index-eng.html">Parliamentary Precinct</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/bi-rp/index-eng.html">Real Property</a></li>
	<li><a href="http://btb.gc.ca/btb.php?lang=eng&cont=001">Translation Bureau</a></li>
  </ul>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/st-ps/index-eng.html"><strong><abbr title="Public Works and Government Services Canada">PWGSC</abbr> Services - Main page</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/regions-eng.html"><strong>Regions</strong></a></h3><div class="mb-sm">
<div class="span-2">
  <ul>
	<li><a href="http://intranet.atl.pwgsc.gc.ca/breakers-brisants/home-accueil">Atlantic</a></li>
	<li><a href="http://orion.pwgsc-tpsgc.gc.ca/ont/index-eng.cfm">Ontario</a></li>
	<li><a href="http://pacific.pwgsc.gc.ca/">Pacific</a></li>
	<li><a href="http://gasoti-amitos.que.tpsgc.gc.ca/entrenous/accueil_home/tabid/292/language/en-CA/Default.aspx">Quebec</a></li>
	<li><a href="http://thewire.wst.pwgsc.gc.ca/default.aspx">Western</a></li>
  </ul>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/regions-eng.html"><strong>Regions - Main page</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/index-eng.html"><strong>Resources</strong></a></h3><div class="mb-sm">
<div class="span-2">
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/az-index-eng.html">A to Z Index</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/cn-cu-eng.html">Contact Us</a></li>
	<li><a href="http://publiservice.tpsgc-pwgsc.gc.ca/forms/text/index-e.html">Forms</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/faq-eng.html">Frequently Asked Questions</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/politiques-policies-eng.html">Policies</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/publications-eng.html">Publications and Reports</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/site-eng.html">Site Map</a></li>
  </ul>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/index-eng.html"><strong>Resources - Main page</strong></a></div>
</div></section></li>

<!-- DataAjaxFragmentEnd -->
</html>