<!DOCTYPE html>
<html lang="en">
<!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
wet-boew.github.com/wet-boew/License-eng.txt / wet-boew.github.com/wet-boew/Licence-fra.txt -->
<!-- DataAjaxFragmentStart -->

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html"><strong>Centre de travail</strong></a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html#outils"><strong>Outils</strong></a></h4>
  <ul>
	<li><a href="https://achatsendirect-e-purchasing.gc.ca/ECAT.formproc?/ECAT?">Achats en ligne</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/direction/approvisionnements/text/ofpt-f.html">Outils d'approvisionnement</a></li>
	<li><a href="http://www.tpsgc-pwgsc.gc.ca/biens-property/sngp-npms/index-fra.html">Syst&egrave;me national de gestion de projet</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/finance/text/sigma/index-fra.html">Syst&egrave;me Sigma</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html#dr"><strong>Documents de r&eacute;f&eacute;rence</strong></a></h4>
  <ul>
	<li><a href="https://achatsetventes.gc.ca/politiques-et-lignes-directrices/Guide-des-approvisionnements">Guide des approvisionnements</a></li>
	<li><a href="http://publiservice.tpsgc-pwgsc.gc.ca/rg/manuels-manuals/index-fra.html">Manuel du receveur g&eacute;n&eacute;ral</a></li>
	<li><a href="http://publiservice.tpsgc-pwgsc.gc.ca/ipm-dpi/index-fra.html">Politiques minist&eacute;rielles</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/finance/text/ges-man/taux-rates-fra.html">Taux d'int&eacute;r&ecirc;t</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html#st"><strong>Soutien technique</strong></a></h4>
  <ul>
	<li><a href="http://ossro-dsbl.etg.gc.ca/pwgsc/start.aspx?lang=fr">Demande de service de <abbr title="technologie de l'information">TI</abbr></a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/ti-it/mv-vm/index-fra.html">&Eacute;tablissement du courrier &eacute;lectronique et de la messagerie vocale</a></li>
	<li><a href="http://csti-itsc.tpsgc-pwgsc.gc.ca/iprint/index.aspx?lang=fra">Installation d'une imprimante r&eacute;seau</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/ti-it/mpls-pss/text/main-f.html">R&eacute;initialisation du mot de passe</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html#si"><strong>Services internes</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/direction/cspc/dsg-cs/text/mtrl-f.html#s1">Carte d'achat</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/direction/cspc/cims/sgc-mms/crr-f.html">Courrier et messagerie</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/direction/cspc/dsg-cs/text/mnstrcrprt-f.html">Espace de bureau</a></li>
	<li><a href="http://btb.gc.ca/btb.php?lang=fra&cont=268">Traduction et terminologie</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html#comms"><strong>Communications</strong></a></h4>
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/ps-fra.html">&Eacute;v&eacute;nements</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/immng-clsg-fra.html">Image de marque</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/ms-sm/ms-sm-fra.html">M&eacute;dias sociaux</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/rm-mr-fra.html">Relations avec les m&eacute;dias</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html#va"><strong>Voyages d'affaires</strong></a></h4>
  <ul>
	<li><a href="http://rehelv-acrd.tpsgc-pwgsc.gc.ca/index-fra.aspx">H&eacute;bergement</a></li>
	<li><a href="http://rehelv-acrd.tpsgc-pwgsc.gc.ca/rechercher-search-4-fra.aspx">Location de v&eacute;hicules</a></li>
	<li><a href="http://publiservice.tpsgc-pwgsc.gc.ca/bi-rp/publications/stat-park-f.html">Stationnement</a></li>
	<li><a href="https://sts-tav.gc.ca/index-fra.html">Travel AcXess</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html#is"><strong>Installations et s&eacute;curit&eacute;</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dsm-csd/persec-secpers-fra.html">Cartes d'identit&eacute;</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/planevacu-evacuplan-fra.html">&Eacute;vacuation d'urgence</a></li>
	<li><a href="https://reservations.pwgsc.gc.ca/welcome.cfm?language=FRENCH">R&eacute;servation de salle de conf&eacute;rence</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dsm-csd/index-fra.html">S&eacute;curit&eacute; minist&eacute;rielle</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html#cg"><strong>Centre de gestion</strong></a></h4>
  <ul>
	<li><a href="http://source-app.tpsgc-pwgsc.gc.ca/dotationexpress-expressstaffing/text/index-fra.cfm">Dotation express</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/rendement-performance/gr-pm-fra.html">Gestion du rendement</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/planification-planning/planification-planning-fra.html">Planification des ressources humaines</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/vousetes-areyou/gestionnaires-manager-fra.html">Ressources pour les gestionnaires</a></li>
  </ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ct-wc/index-fra.html"><strong>Centre de travail - Page principale</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html"><strong>Coin des employ&eacute;s</strong></a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html#pp"><strong>Paye et pension</strong></a></h4>
  <ul>
	<li><a href="http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/awr-cwa/index-fra.html">Applications Web de la r&eacute;mun&eacute;ration</a></li>
	<li><a href="http://pensionetavantages-pensionandbenefits.gc.ca/accueil-home-fra.html">Pension</a></li>
	<li><a href="http://publiservice.tbs-sct.gc.ca/pubs_pol/hrpubs/coll_agre/rates-taux-fra.asp">Taux de r&eacute;mun&eacute;ration</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html#asa"><strong>Avantages sociaux et assurance</strong></a></h4>
  <ul>
	<li><a href="http://www.tbs-sct.gc.ca/hr-rh/bp-rasp/benefits-avantages/dip-rai/dip-rai-fra.asp">Assurance-invalidit&eacute;</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/avantages-benefits/conges-leave/conges-leave-fra.html">Cong&eacute;</a></li>
	<li><a href="http://publiservice.tbs-sct.gc.ca/hr-rh/bp-rasp/mb-mav/pml-cpcm-fra.asp">Cong&eacute; de maternit&eacute; et cong&eacute; parental</a></li>
	<li><a href="http://publiservice.tbs-sct.gc.ca/pubs_pol/hrpubs/coll_agre/siglist-fra.asp">Conventions collectives</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html#fc"><strong>Formation et carri&egrave;re</strong></a></h4>
  <ul>
	<li><a href="http://www.csps-efpc.gc.ca/index-fra.aspx">&Eacute;cole de la fonction publique du Canada</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/languages/formation-guideline-fra.html">Formation linguistique</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/apprentissage-learning/papms-plpp-fra.html">Plan d'apprentissage personnel</a></li>
	<li><a href="http://coursebrowser.pwgsc.gc.ca/welcome.htm?&language=fr">R&eacute;pertoire des cours</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html#ee"><strong>Embauche et emploi</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/classification/class-org-fra.html">Classification</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/competences-competencies/index-fra.html">Comp&eacute;tences</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/gest-car-manag/index-fra.html">Gestion de carri&egrave;re</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/travail-labour/sites-fra.html">Syndicats</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html#sme"><strong>Sant&eacute; et mieux-&ecirc;tre</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/equit-divers/opma-da-fra.html">Aides li&eacute;es au travail</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/ergonomie-ergonomics-fra.html">&Eacute;valuation ergonomique</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/soins-aid-fra.html">Premiers soins</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/index-fra.html">Sant&eacute; et s&eacute;curit&eacute; au travail</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html#sprh"><strong>Services et programmes de <abbr title="Ressources humaines">RH</abbr></strong></a></h4>
  <ul> 
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/equit-divers/eme-ee-fra.html">&Eacute;quit&eacute; et diversit&eacute;</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/languages/lo-ol-fra.html">Langues officielles</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/carriere-career/recompenses-awards/recompenses-awards-fra.html">R&eacute;compenses et reconnaissance</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/val-eth/index-fra.html">Valeurs et &eacute;thique</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html#qlmt"><strong>Questions li&eacute;es au milieu de travail</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dgs-dob/di-id/divulgation-disclosure-fra.html">La divulgation interne</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/travail-labour/reglediffer-guidedispres-fra.html">Harc&egrave;lement</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/aide-assistance/paeo-eoap-fra.html">Programme d'aide aux employ&eacute;s et &agrave; l'organisation</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/travail-labour/rt-lr-fra.html">Relations de travail</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/confli/bgcmt-owcm-fra.html">R&eacute;solution des conflits</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html#politiques"><strong>Politiques</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/val-eth/code-cond-fra.html">Code de conduite</a></li>
	<li><a href="http://www.tbs-sct.gc.ca/chro-dprh/pol-fra.asp">Conseil du Tr&eacute;sor</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/philo-fra.html">Philosophie et engagements</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/lstpolsst-lstpolhas-fra.html">Sant&eacute; et la s&eacute;curit&eacute; au travail</a></li>
  </ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ce-ec/index-fra.html"><strong>Coin des employ&eacute;s - Page principale</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-fra.html"><strong>Nouvelles</strong></a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-fra.html#nn"><strong>Nouvelles nationales</strong></a></h4>
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/smsmd-dmadm/index-fra.html">De la part du <abbr title="Sous-ministre">SM</abbr> et du <abbr title="sous-ministre d&eacute;l&eacute;gu&eacute;e">SMD</abbr></a></li>
	<li><a href="http://www.infomedia.gc.ca/pwgsc-tpsgc/index-fra.aspx">InfoM&eacute;dia</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/mm-mm/index-fra.html">Message de la ministre</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/dlc-ink/index-fra.html"><abbr title="Travaux publics et Services gouvernementaux Canada">TPSGC</abbr> dans le coup</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-fra.html#nm"><strong>Nouvelles minist&eacute;rielles</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/bi-rp/bulletin-newsletter/index-fra.html">Biens immobiliers</a></li>
	<li><a href="http://atrium.gc.ca/atrium.php?page=nouvelles_news&lang=fr">Bureau de la traduction</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/finance/index-fra.html">Finances</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/ssc-css/bulletinssc-css-fra.html">Strat&eacute;gie de service &agrave; la client&egrave;le</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/sit-its/aprps-abt/vdtt-fcs/index-fra.html">Technologie de l'information</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-fra.html#nr"><strong>Nouvelles r&eacute;gionales</strong></a></h4>
  <ul>
    <li><a href="http://intranet.atl.tpsgc.gc.ca/breakers-brisants/home-accueil">Atlantique</a></li>
    <li><a href="http://orion.ont.pwgsc.gc.ca/ont/news-nouvelles/index-fra.cfm">Ontario</a></li>
    <li><a href="http://thewire.wst.pwgsc.gc.ca/news/mynews/rextra.aspx">Ouest</a></li>
    <li><a href="http://renew.pac.pwgsc.gc.ca/applications/news/index.cfm">Pacifique</a></li>
    <li><a href="http://gasoti-amitos.que.tpsgc.gc.ca/entrenous/oeil_glimpse/dernnouvlatestnews/tabid/665/language/fr-CA/Default.aspx">Qu&eacute;bec</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-fra.html#evenements"><strong>&Eacute;v&eacute;nements</strong></a></h4>
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/dlc-ink/ce-ec/index-fra.html">Calendrier d'&eacute;v&eacute;nements</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/ccmtgc-gcwcc/index-fra.html">Campagne de charit&eacute; en milieu de travail du gouvernement du Canada (CCMTGC)</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/smsmd-dmadm/2020/index-fra.html">Objectif 2020</a></li>
  </ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/nouvelles-news/index-fra.html"><strong>Nouvelles - Page principale</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-fra.html"><strong>Collectivit&eacute;s</strong></a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-fra.html#reseaux"><strong>R&eacute;seaux</strong></a></h4>
  <ul>
	<li><a href="http://rcg-mcn.tpsgc.gc.ca/index.cfm/fra/">Collectivit&eacute; des gestionnaires</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/quisommes-whoweare/fierte-pride-fra.html">FIERT&Eacute; au travail</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rnj-nyn/index-fra.html">Jeunes</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/quisommes-whoweare/minorites-minorities-fra.html">Minorit&eacute;s visibles</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/quisommes-whoweare/handicap-disabil-fra.html">Personnes handicap&eacute;es</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/quisommes-whoweare/autochtones-aboriginal-fra.html">Peuples autochtones</a></li>
  </ul>
</section>
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-fra.html#ms"><strong>M&eacute;dias sociaux</strong></a></h4>
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/bhd-slb/index-fra.html">Blogue de la haute direction</a></li>
	<li><a href="http://elgg.srv.gc.ca/elgg17/">GCConnex</a></li>
	<li><a href="http://www.gcforums.gc.ca/default.aspx?l=f">GCForums</a></li>
	<li><a href="http://www.gcpedia.gc.ca/gcwiki/index.php?title=Main%20Page&setlang=fr&uselang=fr">GCPedia</a></li>
	<li><a href="http://infowiki.tpsgc-pwgsc.gc.ca/homepage.action?lang=fra">Infowiki</a></li>
	<li lang="en" xml:lang="en"><a href="http://twitter.com/@TPSGC_PWGSC">Twitter</a></li>
  </ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-fra.html#comites"><strong>Comit&eacute;s</strong></a></h4>
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/travail-labour/afpc-psac-fra.html">Alliance de la Fonction publique du Canada&nbsp;&ndash; Comit&eacute;s de consultation</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/milieutravail-workplace/equit-divers/cceme-jcee-fra.html">Comit&eacute; conjoint sur l'&eacute;quit&eacute; en mati&egrave;re d'emploi</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/comite-committee-fra.html">Comit&eacute; d'examen pour la gestion d'invalidit&eacute; et les mesures d'adaptation</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/mieuxetre-wellness/sante-health/comitesst-hascommittee-fra.html">Comit&eacute;s de sant&eacute; et s&eacute;curit&eacute; au travail</a></li>
	<li><a href="http://www.gcpedia.gc.ca/wiki/Comit&eacute;_Directeur_PPFE">Initiative de Pr&eacute;sentation et paiement de factures par voie &eacute;lectronique Comit&eacute; directeur</a></li>
  </ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/collectivites-communities/index-fra.html"><strong>Collectivit&eacute;s - Page principale</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/st-ps/index-fra.html"><strong>Services de <abbr title="Travaux publics et Services gouvernementaux Canada">TPSGC</abbr></strong></a></h3><div class="mb-sm">
<div class="span-2">
  <ul>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/direction/approvisionnements/text/index-f.html">Approvisionnements</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/bi-rp/index-fra.html">Biens immobiliers</a></li>
	<li><a href="http://btb.gc.ca/btb.php?lang=fra&cont=001">Bureau de la traduction</a></li>
	<li><a href="http://www.tpsgc-pwgsc.gc.ca/collineduparlement-parliamenthill/index-fra.html">Cit&eacute; parlementaire</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/communications/index-fra.html">Communications</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/direction/abc/text/index-f.html">Comptabilit&eacute;, Gestion bancaire et R&eacute;mun&eacute;ration</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/finance/index-fra.html">Finances</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/rh-hr/index-fra.html">Ressources humaines</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/sit-its/index-fra.html">Services d'infotechnologie</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dgsi-isb/index-fra.html">Services int&eacute;gr&eacute;s</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/direction/cspc/text/index-f.html">Services minist&eacute;riels et politiques strat&eacute;giques</a></li>
	<li><a href="http://source.tpsgc-pwgsc.gc.ca/dgs-dob/index-fra.html">Surveillance minist&eacute;rielle</a></li>
  </ul>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/st-ps/index-fra.html"><strong>Services de <abbr title="Travaux publics et Services gouvernementaux Canada">TPSGC</abbr> - Page principale</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/regions-fra.html"><strong>R&eacute;gions</strong></a></h3><div class="mb-sm">
<div class="span-2">
  <ul>
	<li><a href="http://intranet.atl.tpsgc.gc.ca/breakers-brisants/home-accueil">Atlantique</a></li>
	<li><a href="http://orion.pwgsc-tpsgc.gc.ca/ont/index-fra.cfm">Ontario</a></li>
	<li><a href="http://thewire.wst.pwgsc.gc.ca/default.aspx">Ouest</a></li>
	<li><a href="http://pacific.pwgsc.gc.ca/">Pacifique</a></li>
	<li><a href="http://gasoti-amitos.que.tpsgc.gc.ca/entrenous/accueil_home/tabid/292/language/fr-CA/Default.aspx">Qu&eacute;bec</a></li>
  </ul>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/apropos-about/regions-fra.html"><strong>R&eacute;gions - Page principale</strong></a></div>
</div></section></li>

<li><section><h3><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/index-fra.html"><strong>Ressources</strong></a></h3><div class="mb-sm">
<div class="span-2">
  <ul>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/cn-cu-fra.html">Contactez-nous</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/faq-fra.html">Foire aux questions</a></li>
	<li><a href="http://publiservice.tpsgc-pwgsc.gc.ca/forms/text/index-f.html">Formulaires</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/az-index-fra.html">Index A-Z</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/site-fra.html">Plan du site</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/politiques-policies-fra.html">Politiques</a></li>
	<li><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/publications-fra.html">Publications et rapports</a></li>
  </ul>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://intranet.tpsgc-pwgsc.gc.ca/intranet/ressources-resources/index-fra.html"><strong>Ressources - Page principale</strong></a></div>
</div></section></li>

<!-- DataAjaxFragmentEnd -->
</html>